name: roadguardian_client
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons
  cupertino_icons: ^1.0.8

  # Flutter Map (OpenStreetMap)
  flutter_map: ^4.0.0
  latlong2: ^0.8.1

  # Volume Controller compatibile Dart 3.x
  volume_controller: ^3.4.0

  # Per ottenere la posizione GPS
  geolocator: ^10.1.0

  # Permessi runtime compatibile Flutter vecchio


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
